### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by trevius** [micheleriva/Salvini-Blocker#1]
I see Salvini...

https://www.ecosia.org/images?q=matteo+salvini#id=_

**Comment by micheleriva** [comment]
Hi @trevius 	,
thanks for reporting this.
It seems that it doesn't work on Ecosia as search engine, can you please try on Google just for testing purposes?

Btw I'm gonna fix this asap!

**Comment by trevius** [comment]
It's better but not perfect 100% :) I use Ecosia to help trees :)

[image: image.png]

Are you italian like me?

Il giorno ven 14 giu 2019 alle ore 15:50 λ Sleva <notifications@github.com>
ha scritto:

**Comment by micheleriva** [comment]
I do often use Ecosia for the same reason 😄 
Yes I'm from Monza!

**Comment by trevius** [comment]
Mmmmmmmonza :) piacere, io sono di Roma, anche se vivo tra Parma e Reggio
Emilia!

Il giorno ven 14 giu 2019 alle ore 15:57 λ Sleva <notifications@github.com>
ha scritto:

**Comment by micheleriva** [comment]
@trevius 	I've fixed the issue with Ecosia, it will be live in a few days 🎉 
Thank you again for your report!

ps. I'm sorry if I'm still writing in english, GitHub is a technical portal for developers and it may be useful for other people to read what we're talking about 😄 
If you need something else or just keep in touch, you can find me on LinkedIn https://linkedin.com/in/micheleriva95/ or my website https://www.micheleriva.it

have a nice day!
