### ISSUE TITLE
Help to improve the Salvini Blocker

### ISSUE THREAD

**Issue by Darkmiaoo** [micheleriva/Salvini-Blocker#3]
Hey, I don't really know anything about programming, but I guess there could be a way to help you 'sending you' the images that the program doesnt recognize even if they dont contain the word 'salvini'. Is there anything I can do to signal you the images I find?

Thanks for your work! It's funny and I get less mad when I open my facebook

**Comment by micheleriva** [comment]
Hey @Darkmiaoo thanks a lot for your message!
Are you a developer? I need some help maintaining the code 😄 
otherwise feel free to send the URL of the page where the image is not replaced.

Thanks a lot!! 😄
